import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import { Bot, User, Send, Loader2, Sparkles, AlertCircle, Trash2 } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export function AiCopilotPage() {
  const { token } = useAuth();
  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: 'assistant',
      text: 'Greetings. I am JARVIS (Just A Rather Very Intelligent Security Assistant), your dedicated Identity Security Copilot for Stark Industries IAM Lab. How may I assist your investigation or SIEM analysis today?'
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading]);

  const handleClearChat = () => {
    setMessages([
      {
        id: Date.now(),
        sender: 'assistant',
        text: 'Chat history cleared. Greetings! I am JARVIS. How may I assist your security analysis?'
      }
    ]);
    setError(null);
  };

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMessageText = input.trim();
    const userMsg = {
      id: Date.now(),
      sender: 'user',
      text: userMessageText
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setLoading(true);
    setError(null);

    const authToken = token || localStorage.getItem('kc_token');
    const payload = { message: userMessageText };
    const requestHeaders = {
      Authorization: authToken ? `Bearer ${authToken}` : '',
      'Content-Type': 'application/json'
    };

    try {
      // Primary attempt via 127.0.0.1 (bypasses Windows IPv6 localhost resolution delays)
      let response;
      try {
        response = await axios.post(
          'http://127.0.0.1:5000/api/ai/chat',
          payload,
          {
            timeout: 60000,
            headers: requestHeaders
          }
        );
      } catch (primaryErr) {
        // Fallback to localhost if 127.0.0.1 is unreachable
        response = await axios.post(
          'http://localhost:5000/api/ai/chat',
          payload,
          {
            timeout: 60000,
            headers: requestHeaders
          }
        );
      }

      const assistantMsg = {
        id: Date.now() + 1,
        sender: 'assistant',
        text: response.data?.response || 'No response generated by JARVIS.'
      };

      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err) {
      console.error('[JARVIS Copilot Error]', err);
      const errMsg = err.response?.data?.message || err.response?.data?.error || err.message || 'Request timed out or failed to connect to backend server.';
      setError(errMsg);

      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          sender: 'assistant',
          isError: true,
          text: `JARVIS Notice: ${errMsg}`
        }
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-6.5rem)] bg-soc-bg space-y-4">
      {/* Page Header */}
      <div className="flex items-center justify-between pb-3 border-b border-soc-border shrink-0">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <Sparkles size={20} className="text-cyan-400" />
            JARVIS Security Copilot
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            J.A.R.V.I.S. (Just A Rather Very Intelligent Security Assistant) — IAM & SIEM Intelligence Engine.
          </p>
        </div>
        <button
          onClick={handleClearChat}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-soc-card hover:bg-soc-inset border border-soc-border text-slate-400 hover:text-slate-200 rounded-lg transition"
          title="Clear Chat Session"
        >
          <Trash2 size={14} />
          <span>Clear Chat</span>
        </button>
      </div>

      {/* Error Alert if any */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 text-red-400 text-xs p-3 rounded-lg flex items-center gap-2 shrink-0">
          <AlertCircle size={16} className="shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Chat Messages Window */}
      <div className="flex-1 overflow-y-auto bg-soc-card border border-soc-border rounded-xl p-4 space-y-4 shadow-inner">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex gap-3 text-xs ${
              msg.sender === 'user' ? 'justify-end' : 'justify-start'
            }`}
          >
            {msg.sender === 'assistant' && (
              <div className="w-7 h-7 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400 shrink-0 mt-0.5" title="JARVIS">
                <Bot size={16} />
              </div>
            )}

            <div
              className={`max-w-[75%] rounded-xl p-3.5 leading-relaxed font-sans shadow ${
                msg.sender === 'user'
                  ? 'bg-cyan-600 text-slate-950 font-medium rounded-tr-none'
                  : msg.isError
                  ? 'bg-red-950/40 border border-red-500/30 text-red-300 rounded-tl-none'
                  : 'bg-soc-inset border border-soc-border text-slate-200 rounded-tl-none whitespace-pre-wrap'
              }`}
            >
              {msg.text}
            </div>

            {msg.sender === 'user' && (
              <div className="w-7 h-7 rounded-lg bg-slate-700 border border-slate-600 flex items-center justify-center text-slate-200 shrink-0 mt-0.5">
                <User size={16} />
              </div>
            )}
          </div>
        ))}

        {/* Loading Spinner Bubble */}
        {loading && (
          <div className="flex gap-3 text-xs justify-start">
            <div className="w-7 h-7 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400 shrink-0">
              <Bot size={16} />
            </div>
            <div className="bg-soc-inset border border-soc-border text-slate-400 p-3 rounded-xl rounded-tl-none flex items-center gap-2">
              <Loader2 size={14} className="animate-spin text-cyan-400" />
              <span>JARVIS is analyzing security telemetry...</span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Bar */}
      <form onSubmit={handleSendMessage} className="flex gap-2 shrink-0">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          disabled={loading}
          placeholder="Ask JARVIS (e.g. 'Show failed logins today' or 'Explain LOGIN_ERROR')..."
          className="flex-1 bg-soc-card border border-soc-border rounded-xl px-4 py-3 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-soc-accent transition disabled:opacity-50"
        />
        <button
          type="submit"
          disabled={loading || !input.trim()}
          className="px-5 py-3 rounded-xl bg-soc-accent hover:bg-cyan-600 disabled:opacity-50 text-slate-950 font-bold text-xs shadow-lg transition flex items-center gap-2 shrink-0"
        >
          {loading ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
          <span>Send</span>
        </button>
      </form>
    </div>
  );
}

export default AiCopilotPage;
